#!/bin/bash
apt update 
apt upgrade -y
apt install curl xz-utils -y

rm -rf /usr/local/node

curl -O -J -L https://nodejs.org/dist/v22.15.1/node-v22.15.1-linux-x64.tar.xz
tar -xvf node*.tar.xz
rm -rf node*.tar.xz

mv node*/ /usr/local/node

echo 'export PATH=/usr/local/node/bin:$PATH' >> ~/.bashrc
source ~/.bashrc

node -v
npm -v